name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools python3-dev rsync subversion swig time xsltproc zlib1g-dev 
    
    - name: feeds update
      run: ./scripts/feeds update -a
      
    - name: feeds install
      run: ./scripts/feeds install -a
      
    - name: Install dependencies
      run: make -j1 V=s
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
